//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace ExampleCustomAIMLTags.com.fullerdata.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FullerData Fortune CookieSoap", Namespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx")]
    public partial class FullerDataFortuneCookie : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback readNodeCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFortuneCookieOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountCookiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpecificCookieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FullerDataFortuneCookie() {
            this.Url = global::ExampleCustomAIMLTags.Properties.Settings.Default.ExampleCustomAIMLTags_com_fullerdata_www_FullerData_x0020_Fortune_x0020_Cookie;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event readNodeCountCompletedEventHandler readNodeCountCompleted;
        
        /// <remarks/>
        public event GetFortuneCookieCompletedEventHandler GetFortuneCookieCompleted;
        
        /// <remarks/>
        public event CountCookiesCompletedEventHandler CountCookiesCompleted;
        
        /// <remarks/>
        public event GetSpecificCookieCompletedEventHandler GetSpecificCookieCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx/readNodeCount", RequestNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", ResponseNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int readNodeCount() {
            object[] results = this.Invoke("readNodeCount", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void readNodeCountAsync() {
            this.readNodeCountAsync(null);
        }
        
        /// <remarks/>
        public void readNodeCountAsync(object userState) {
            if ((this.readNodeCountOperationCompleted == null)) {
                this.readNodeCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadNodeCountOperationCompleted);
            }
            this.InvokeAsync("readNodeCount", new object[0], this.readNodeCountOperationCompleted, userState);
        }
        
        private void OnreadNodeCountOperationCompleted(object arg) {
            if ((this.readNodeCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readNodeCountCompleted(this, new readNodeCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx/GetFortuneCookie", RequestNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", ResponseNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFortuneCookie() {
            object[] results = this.Invoke("GetFortuneCookie", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFortuneCookieAsync() {
            this.GetFortuneCookieAsync(null);
        }
        
        /// <remarks/>
        public void GetFortuneCookieAsync(object userState) {
            if ((this.GetFortuneCookieOperationCompleted == null)) {
                this.GetFortuneCookieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFortuneCookieOperationCompleted);
            }
            this.InvokeAsync("GetFortuneCookie", new object[0], this.GetFortuneCookieOperationCompleted, userState);
        }
        
        private void OnGetFortuneCookieOperationCompleted(object arg) {
            if ((this.GetFortuneCookieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFortuneCookieCompleted(this, new GetFortuneCookieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx/CountCookies", RequestNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", ResponseNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CountCookies() {
            object[] results = this.Invoke("CountCookies", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CountCookiesAsync() {
            this.CountCookiesAsync(null);
        }
        
        /// <remarks/>
        public void CountCookiesAsync(object userState) {
            if ((this.CountCookiesOperationCompleted == null)) {
                this.CountCookiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountCookiesOperationCompleted);
            }
            this.InvokeAsync("CountCookies", new object[0], this.CountCookiesOperationCompleted, userState);
        }
        
        private void OnCountCookiesOperationCompleted(object arg) {
            if ((this.CountCookiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountCookiesCompleted(this, new CountCookiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx/GetSpecificCookie", RequestNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", ResponseNamespace="http://www.fullerdata.com/FortuneCookie/FortuneCookie.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSpecificCookie(int index) {
            object[] results = this.Invoke("GetSpecificCookie", new object[] {
                        index});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSpecificCookieAsync(int index) {
            this.GetSpecificCookieAsync(index, null);
        }
        
        /// <remarks/>
        public void GetSpecificCookieAsync(int index, object userState) {
            if ((this.GetSpecificCookieOperationCompleted == null)) {
                this.GetSpecificCookieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpecificCookieOperationCompleted);
            }
            this.InvokeAsync("GetSpecificCookie", new object[] {
                        index}, this.GetSpecificCookieOperationCompleted, userState);
        }
        
        private void OnGetSpecificCookieOperationCompleted(object arg) {
            if ((this.GetSpecificCookieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpecificCookieCompleted(this, new GetSpecificCookieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void readNodeCountCompletedEventHandler(object sender, readNodeCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class readNodeCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal readNodeCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetFortuneCookieCompletedEventHandler(object sender, GetFortuneCookieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFortuneCookieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFortuneCookieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void CountCookiesCompletedEventHandler(object sender, CountCookiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountCookiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountCookiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSpecificCookieCompletedEventHandler(object sender, GetSpecificCookieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpecificCookieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpecificCookieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591